vpc_name                                = "myvpc"
vpc_cidr_block                          = "10.0.0.0/16"
vpc_azs                                 = ["eu-west-2a", "eu-west-2b"]
vpc_public_subnets                      = ["10.0.101.0/24", "10.0.102.0/24"]
vpc_private_subnets                     = ["10.0.111.0/24", "10.0.112.0/24"]
vpc_database_subnets                    = ["10.0.121.0/24", "10.0.122.0/24"]
vpc_create_database_subnet_group        = true 
vpc_create_database_subnet_route_table  = true   
vpc_enable_nat_gateway                  = true  
vpc_single_nat_gateway                  = true      # For production level, we would take this false but demo purposes, we use single NAT to save cost
vpc_one_nat_gateway_per_az              = false
